spring.ai.mcp.server.protocol=STREAMABLE
server.port=8081

# Your info
name=Nicky
lastname=Hariniaina
username=ferrissushi
email=ferrissushi@gmail.com
phone.number=0381584053
age=19
gender=Male
location=Madagascar
university=HEI Haute Ecole d'Informatique
major=Computer Science
interests=Programming,AI,MCP,CTF,Drawing,Japanese
